name: Wake Up Portfolio
on:
  schedule:
    - cron: '0 8 * * *'
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Requests
        run: pip install requests

      - name: Run Awakener
        run: python git_wake_up.py
